ALTER TABLE `CarboSense`.`NABEL_DUE` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

# Add triggers

CREATE TRIGGER tg_updated_NABEL_DUE ON NABEL_DUE
AFTER UPDATE FOR EACH ROW
    BEGIN
    SET NEW.modified = CURRENT_TIMESTAMP()
    END;


ALTER TABLE `CarboSense`.`NABEL_HAE` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`NABEL_RIG` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`NABEL_PAY` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`NABEL_RIG` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`EMPA_LAEG` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`UNIBE_BRM` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`UNIBE_GIMM` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`ClimateChamber_00_DUE` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;

ALTER TABLE `CarboSense`.`PressureChamber_00_DUE` 
ADD COLUMN IF NOT EXISTS created TIMESTAMP DEFAULT current_timestamp(),
ADD COLUMN IF NOT EXISTS modified TIMESTAMP DEFAULT NULL;
