HPP:
  source:
    type: DB
    table: hpp_data
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      sensor_id: SensorUnit_ID
    date_column: DATE(FROM_UNIXTIME(time))
    na: -999
  dest:
    type: DB
    table: co2_level2
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      sensor_id: sensor_id
    date_column:  DATE(FROM_UNIXTIME(timestamp))
  columns:
    - {name: time,  source_name: 'time', datatype: int, na: Null}
    - {name: sensor_id, source_name: node, datatype: int, na: Null}
    - {name: battery, source_name: battery, datatype: float, na: 0}     
LP8:
  source:
    type: DB
    table: lp8_data
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      sensor_id: SensorUnit_ID
    date_column: DATE(FROM_UNIXTIME(time))
    column_filter: senseair_lp8_co2 IS NOT NULL
    na: -999
  dest:
    type: DB
    table: co2_level2
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      sensor_id: sensor_id
    date_column:  DATE(FROM_UNIXTIME(timestamp))
    column_filter: CO2 IS NOT NULL
  #The column mapping is not used here
  columns:
    - {name: time,  source_name: 'time', datatype: int, na: Null}
    - {name: sensor_id, source_name: node, datatype: int, na: Null}
    - {name: battery, source_name: battery, datatype: float, na: 0}
Vaisala:
  source:
    type: DB
    table: vaisala_data
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      sensor_id: SensorUnit_ID
    date_column: DATE(FROM_UNIXTIME(time))
    column_filter: vaisala_gmp343_co2 IS NOT NULL
    na: -999
  dest:
    type: DB
    table: co2_level2
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      sensor_id: sensor_id
    date_column:  DATE(FROM_UNIXTIME(timestamp))
    column_filter: CO2 IS NOT NULL
  #The column mapping is not used here
  columns:
    - {name: time,  source_name: 'time', datatype: int, na: Null}
    - {name: sensor_id, source_name: node, datatype: int, na: Null}
    - {name: battery, source_name: battery, datatype: float, na: 0}
