HPP:
  source:
    type: DB
    table: co2_level2
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      node: sensor_id
    timestamp_column: timestamp
    date_column:  DATE(FROM_UNIXTIME(timestamp))
    column_filter: CO2 IS NOT NULL
    na: .NaN
  dest:
    type: influxDB
    db: processed
    table: measurements
    date_from: 2022-01-01T00:00:00.000
    sensors: ['co2']
    grouping_key: 
      node: node
    tags:
      channel: hpp_level_00
      title: 'co2 [ppm]'
      unit: 'ppm'
  columns:
    - {name: time,  source_name: 'timestamp', datatype: int, na: Null}
    - {name: node, source_name: sensor_id, datatype: int, na: Null}
    - {name: CO2, source_name: CO2, datatype: float, na: Null}
LP8:
  source:
    type: DB
    table: co2_level2
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      node: sensor_id
    date_column: DATE(FROM_UNIXTIME(timestamp))
    timestamp_column: timestamp
    column_filter: CO2 IS NOT NULL
    na: -999
  dest:
    type: influxDB
    db: processed
    table: measurements
    sensors: ['co2']
    date_from: 2022-01-01T00:00:00.000
    grouping_key: 
      node: node
    tags:
      channel: lp8_level_00
      title: 'co2 [ppm]'
      unit: 'ppm'
  columns:
    - {name: time,  source_name: 'timestamp', datatype: int, na: Null}
    - {name: node, source_name: sensor_id, datatype: str, na: Null}
    - {name: co2, source_name: CO2, datatype: float, na: Null}

