DUE:
  source:
    type: NABEL
    re: '((DUE Test .*)|(CarboSens.*)|(DUE O3 .*))\.(csv|CSV)'
    path: DUE
    date_from: 2022-01-01T00:00:00.000
    na: ''
  dest:
    type: DB
    table: picarro_data
    db_prefix: CarboSense_MySQL
    date_from: 2022-01-01T00:00:00.000
    date_column: DATE(FROM_UNIXTIME(timestamp))
    grouping_key: LocationName
    group: 'DUE1'
    na: .NAN
  columns:
    - {name: timestamp,  query: 'CAST(strftime(''%s'', date) as integer)', datatype: int, na: .NAN}
    - {name: LocationName, query: "'DUE1'", datatype: str, na: NULL}
    - {name: T, query: 'IIF(TEMP_F IS NULL, TEMP, NULL)', datatype: float, na: .NAN}
    - {name: T_F, query: 'IIF(TEMP_F IS NULL, 1, 0)', datatype: int, na: 0}
    - {name: RH, query: 'IIF(FEUCHT_F IS NULL, FEUCHT, NULL)', datatype: float, na: 0}
    - {name: RH_F, query: 'IIF(FEUCHT_F IS NULL, 1, 0)', datatype: int, na: 0}
    - {name: pressure, query: 'IIF(DRUCK_F IS NULL, DRUCK, NULL)', datatype: float, na: .NAN}
    - {name: pressure_F, query: 'IIF(DRUCK_F IS NULL, 1, 0)', datatype: float, na: .NAN}
    - {name: CO2_DRY, query: 'IIF(CO2_dry_F IS NULL, CO2_dry, NULL)', datatype: float, na: .NAN}
    - {name: CO2, query: 'IIF(CO2_F IS NULL, CO2, NULL)', datatype: float, na: .NAN}
    - {name: CO2_F, query: 'IIF(CO2_F IS NULL, 1, 0)', datatype: int, na: 0}
    - {name: CO2_DRY_F, query: 'IIF(CO2_dry_F IS NULL, 1, 0)', datatype: int, na: 0}
    - {name: H2O, query: 'IIF(H2O_F IS NULL, H2O, NULL)', datatype: float, na: .NAN}
    - {name: H2O_F, query: 'IIF(H2O_F IS NULL, 1, 0)', datatype: int, na: 0}
LAEG:
  source:
    type: DB
    db_prefix: empaGSN
    table: laegern_1min_cal
    date_from: 2022-01-01T00:00:00.000
    na: NULL
    date_column:  DATE(FROM_UNIXTIME(timed / 1000))
  dest:
    type: DB
    table: picarro_data
    db_prefix: CarboSense_MySQL
    date_from: 2022-01-01T00:00:00.000
    date_column: timestamp
    grouping_key: LocationName
    group: 'LAEG'
    na: .NAN
  columns:
    - {name: LocationName, query: ''LAEG'', datatype: str}
    - {name: timestamp, query: timed / 1000, datatype: int, na: 0}
    - {name: CO2, query: CO2_DRY * (1 - H2O/100), datatype: float, na: .NAN}
    - {name: CO2_F, query:  1 - (((VALVEPOS = 5) OR (CO2_DRY IS NULL) OR (H2O IS NULL))), datatype: int, na: 0}
    - {name: CO2_DRY, query: CO2_DRY, datatype: float, na: .NAN}
    - {name: CO2_DRY_F, query: 1 - (((VALVEPOS = 5) OR (CO2_DRY IS NULL))), datatype: int, na: 0}
    - {name: H2O, query: H2O, datatype: float, na: .NAN}
    - {name: H2O_F, query:  1 - isnull(H2O), datatype: int, na: 0}


